name = "vlog"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

# R2 bucket binding
[[r2_buckets]]
binding = "VLOG_VIDEOS"
bucket_name = "vlog-videos"

# KV namespace for video metadata
[[kv_namespaces]]
binding = "VIDEO_METADATA"
id = "135904286bb04fbdb9f27efd36c82977"

# Environment variables
[vars]
R2_PUBLIC_DOMAIN = "https://pub-d6b1d0d23f38453c8b417817d399d2c8.r2.dev"
